In [1]:
import multiprocessing as mp
import shutil
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import wfdb
import wfdb.io
from tqdm import tqdm

----
setup variables

In [2]:
mimic_root = Path('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0')

In [3]:
dataset_root = Path('/home/thulio/projects/masters-research/data')

In [4]:
min_seg_time = 5 * 60

In [5]:
relevant_signals = ['II', 'PLETH', 'ABP']

In [6]:
interfering_codes = (
    '33',
    '40',
    '410',
    '411',
    '412',
    '413',
    '414',
    '42',
    '43',
    '44',
    '458',
    '459',
    '785'
)

In [7]:
diabetes_codes = (
    '250'
)

In [8]:
samples_per_class = 17

----
create headers table

In [9]:
p_folders = sorted([f for g in mimic_root.iterdir() if g.is_dir() for f in g.iterdir() if f.is_dir()])
p_folders

[PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000020'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000030'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000033'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000052'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000079'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000085'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000107'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000109'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000123'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000124'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000125'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000135'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000138'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000145'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000154'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000160'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000177'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000184'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000188'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000194'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000208'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000214'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000217'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000222'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000262'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000263'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000271'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000279'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000283'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000292'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000298'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000301'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000302'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000308'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000317'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000318'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000328'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000333'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000357'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000369'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000377'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000379'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000402'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000406'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000408'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000409'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000416'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000422'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000427'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000439'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000462'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000470'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000491'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000495'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000507'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000515'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000518'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000521'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000523'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000543'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000549'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000550'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000565'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000571'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000586'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000593'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000600'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000605'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000608'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000618'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000625'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000631'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000634'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000638'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000639'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000650'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000652'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000666'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000668'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000670'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000672'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000682'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000689'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000695'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000700'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000703'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000708'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000710'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000719'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000735'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000736'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000743'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000747'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000749'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000770'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000772'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000773'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000776'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000784'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000787'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000793'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000798'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000801'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000808'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000818'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000822'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000834'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000843'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000849'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000852'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000865'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000870'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000871'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000875'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000878'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000886'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000891'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000894'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000895'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000901'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000906'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000907'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000925'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000946'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000948'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000952'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000963'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000974'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000981'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p000992'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001002'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001004'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001006'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001012'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001021'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001028'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001029'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001030'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001033'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001038'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001042'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001044'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001046'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001049'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001072'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001075'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001083'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001092'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001097'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001104'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001121'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001123'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001135'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001143'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001144'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001158'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001160'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001170'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001174'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001182'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001190'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001192'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001200'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001207'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001217'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001222'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001224'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001226'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001241'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001244'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001257'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001279'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001280'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001313'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001331'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001337'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001338'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001347'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001354'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001357'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001378'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001396'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001398'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001408'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001409'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001414'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001418'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001430'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001438'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001449'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001453'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001457'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001459'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001474'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001476'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001485'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001501'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001502'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001521'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001524'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001526'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001528'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001531'),
 PosixPath('/home/thulio/Downloads/mimic/physionet.org/files/mimic3wdb-matched/1.0/p00/p001546'),

In [10]:
def process_subject_headers(p_folder: Path):
    master_files = [file for file in p_folder.iterdir() if file.name.startswith('p') and not file.name.endswith('n.hea')]
    segment_data = []
    for master_file in master_files:
        try:
            master_header = wfdb.io.rdheader(master_file.as_posix().replace('.hea', ''), rd_segments=True)
        except (FileNotFoundError, TypeError):
            continue
        subject_id_str, record_start_str = master_file.name.split('-', 1)
        subject_id = int(subject_id_str[1:])
        record_start = pd.to_datetime(record_start_str.replace('.hea', ''), format='%Y-%m-%d-%H-%M')
        for seg in master_header.segments:
            seg: wfdb.io.Record | None
            if seg is not None and not seg.record_name.endswith('layout'):
                segment_data.append({
                    'subject_id': subject_id,
                    'record_start': record_start,
                    'segment_id': seg.record_name,
                    'segment_time': seg.sig_len / seg.fs,
                    'segment_signals': seg.sig_name,
                    'master_id': master_file.stem,
                })
    return segment_data


with mp.Pool(10) as p:
    data = list(tqdm(p.imap_unordered(func=process_subject_headers, iterable=p_folders), total=len(p_folders)))
df_waveforms = pd.DataFrame([y for x in data for y in x])
df_waveforms['record_start'] = pd.to_datetime(df_waveforms['record_start'])
df_waveforms

100%|██████████| 10282/10282 [02:15<00:00, 76.13it/s]

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id
0,30,2172-10-16 12:22:00,3524877_0001,3600.000,"[II, V]",p000030-2172-10-16-12-22
1,33,2116-12-25 13:11:00,3737936_0001,3060.000,"[II, MCL1]",p000033-2116-12-25-13-11
2,33,2116-12-24 12:35:00,3713820_0001,120.000,"[II, MCL1]",p000033-2116-12-24-12-35
3,33,2116-12-24 12:35:00,3713820_0002,27036.504,"[II, MCL1]",p000033-2116-12-24-12-35
4,33,2116-12-24 12:35:00,3713820_0003,53603.496,"[II, MCL1]",p000033-2116-12-24-12-35
...,...,...,...,...,...,...
856334,99383,2131-06-12 18:28:00,3912142_0013,16890.000,"[RESP, CVP, ABP, PLETH, II, I, V]",p099383-2131-06-12-18-28
856335,99383,2131-06-12 18:28:00,3912142_0014,28.000,"[RESP, CVP, ABP, II, I, V]",p099383-2131-06-12-18-28
856336,99383,2131-06-12 18:28:00,3912142_0015,20274.000,"[RESP, CVP, ABP, PLETH, II, I, V]",p099383-2131-06-12-18-28
856337,99383,2131-06-12 18:28:00,3912142_0016,15.000,"[RESP, CVP, ABP, II, I, V]",p099383-2131-06-12-18-28
856338,99383,2131-06-12 18:28:00,3912142_0017,24768.000,"[RESP, CVP, ABP, PLETH, II, I, V]",p099383-2131-06-12-18-28

In [11]:
df_waveforms.to_csv('csvs/waveforms.csv', index=False)

----

In [10]:
df_waveforms = pd.read_csv('csvs/waveforms.csv', parse_dates=['record_start'])
df_waveforms

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id
0,30,2172-10-16 12:22:00,3524877_0001,3600.000,"['II', 'V']",p000030-2172-10-16-12-22
1,33,2116-12-25 13:11:00,3737936_0001,3060.000,"['II', 'MCL1']",p000033-2116-12-25-13-11
2,33,2116-12-24 12:35:00,3713820_0001,120.000,"['II', 'MCL1']",p000033-2116-12-24-12-35
3,33,2116-12-24 12:35:00,3713820_0002,27036.504,"['II', 'MCL1']",p000033-2116-12-24-12-35
4,33,2116-12-24 12:35:00,3713820_0003,53603.496,"['II', 'MCL1']",p000033-2116-12-24-12-35
...,...,...,...,...,...,...
856334,99383,2131-06-12 18:28:00,3912142_0013,16890.000,"['RESP', 'CVP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856335,99383,2131-06-12 18:28:00,3912142_0014,28.000,"['RESP', 'CVP', 'ABP', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856336,99383,2131-06-12 18:28:00,3912142_0015,20274.000,"['RESP', 'CVP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856337,99383,2131-06-12 18:28:00,3912142_0016,15.000,"['RESP', 'CVP', 'ABP', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856338,99383,2131-06-12 18:28:00,3912142_0017,24768.000,"['RESP', 'CVP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28

In [11]:
valid_segment_time = df_waveforms['segment_time'] > min_seg_time
valid_segment_signals = df_waveforms['segment_signals'].apply(lambda sl: all([sig in sl for sig in relevant_signals]))
df_waveforms_filt = df_waveforms[valid_segment_time & valid_segment_signals]
df_waveforms_filt

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id
154,160,2174-11-06 10:12:00,3531764_0003,10789.0,"['RESP', 'PLETH', 'II', 'V', 'AVR', 'ABP']",p000160-2174-11-06-10-12
646,188,2162-01-10 18:53:00,3285727_0007,17396.0,"['PLETH', 'ABP', 'RESP', 'II', 'V', 'AVR']",p000188-2162-01-10-18-53
648,188,2162-01-10 18:53:00,3285727_0009,44047.0,"['PLETH', 'ABP', 'RESP', 'II', 'V', 'AVR']",p000188-2162-01-10-18-53
650,188,2162-01-10 18:53:00,3285727_0011,537.0,"['PLETH', 'ABP', 'RESP', 'II', 'V', 'AVR']",p000188-2162-01-10-18-53
652,188,2162-01-10 18:53:00,3285727_0013,3487.0,"['PLETH', 'ABP', 'RESP', 'II', 'V', 'AVR']",p000188-2162-01-10-18-53
...,...,...,...,...,...,...
856331,99383,2131-06-12 18:28:00,3912142_0010,6007.0,"['RESP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856332,99383,2131-06-12 18:28:00,3912142_0011,3463.0,"['RESP', 'CVP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856334,99383,2131-06-12 18:28:00,3912142_0013,16890.0,"['RESP', 'CVP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856336,99383,2131-06-12 18:28:00,3912142_0015,20274.0,"['RESP', 'CVP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28
856338,99383,2131-06-12 18:28:00,3912142_0017,24768.0,"['RESP', 'CVP', 'ABP', 'PLETH', 'II', 'I', 'V']",p099383-2131-06-12-18-28

----
load mimic tables

In [12]:
df_admissions = pd.read_csv('/home/thulio/Downloads/mimic/ADMISSIONS.csv',
                            index_col='ROW_ID',
                            parse_dates=['ADMITTIME', 'DISCHTIME', 'DEATHTIME', 'EDREGTIME', 'EDOUTTIME']).sort_index()
df_admissions

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
ROW_ID,,,,,,,,,,,,,,,,,,
1,2,163353,2138-07-17 19:04:00,2138-07-21 15:48:00,NaT,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,NaN,NOT SPECIFIED,NaN,ASIAN,NaT,NaT,NEWBORN,0,1
2,3,145834,2101-10-20 19:08:00,2101-10-31 13:58:00,NaT,EMERGENCY,EMERGENCY ROOM ADMIT,SNF,Medicare,NaN,CATHOLIC,MARRIED,WHITE,2101-10-20 17:09:00,2101-10-20 19:24:00,HYPOTENSION,0,1
3,4,185777,2191-03-16 00:28:00,2191-03-23 18:41:00,NaT,EMERGENCY,EMERGENCY ROOM ADMIT,HOME WITH HOME IV PROVIDR,Private,NaN,PROTESTANT QUAKER,SINGLE,WHITE,2191-03-15 13:10:00,2191-03-16 01:10:00,"FEVER,DEHYDRATION,FAILURE TO THRIVE",0,1
4,5,178980,2103-02-02 04:31:00,2103-02-04 12:15:00,NaT,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,NaN,BUDDHIST,NaN,ASIAN,NaT,NaT,NEWBORN,0,1
5,6,107064,2175-05-30 07:15:00,2175-06-15 16:00:00,NaT,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaT,NaT,CHRONIC RENAL FAILURE/SDA,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58972,99985,176670,2181-01-27 02:47:00,2181-02-12 17:05:00,NaT,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Private,ENGL,JEWISH,MARRIED,WHITE,2181-01-26 23:35:00,2181-01-27 04:18:00,FEVER,0,1
58973,99991,151118,2184-12-24 08:30:00,2185-01-05 12:15:00,NaT,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaT,NaT,DIVERTICULITIS/SDA,0,1
58974,99992,197084,2144-07-25 18:03:00,2144-07-28 17:56:00,NaT,EMERGENCY,CLINIC REFERRAL/PREMATURE,SNF,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,2144-07-25 13:40:00,2144-07-25 18:50:00,RETROPERITONEAL HEMORRHAGE,0,1
58975,99995,137810,2147-02-08 08:00:00,2147-02-11 13:15:00,NaT,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaT,NaT,ABDOMINAL AORTIC ANEURYSM/SDA,0,1
58976,99999,113369,2117-12-30 07:15:00,2118-01-04 16:30:00,NaT,ELECTIVE,PHYS REFERRAL/NORMAL DELI,SNF,Medicare,SPAN,JEHOVAH'S WITNESS,SEPARATED,HISPANIC OR LATINO,NaT,NaT,SPONDYLOLISTHESIS/SDA,0,1

In [13]:
df_diagnoses = pd.read_csv('/home/thulio/Downloads/mimic/DIAGNOSES_ICD.csv', index_col='ROW_ID').dropna().sort_index()
df_diagnoses

        SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
ROW_ID
1                2   163353      1.0     V3001
2                2   163353      2.0      V053
3                2   163353      3.0      V290
4                3   145834      1.0      0389
5                3   145834      2.0     78559
...            ...      ...      ...       ...
651043       99999   113369      1.0     75612
651044       99999   113369      2.0      7861
651045       99999   113369      3.0      4019
651046       99999   113369      4.0     25000
651047       99999   113369      5.0      4139

[651000 rows x 4 columns]

----
final processing

In [14]:
df_diagnoses_proc = df_diagnoses.copy()
df_diagnoses_proc['code_interf'] = df_diagnoses_proc['ICD9_CODE'].str.startswith(interfering_codes)
df_diagnoses_proc['code_diab'] = df_diagnoses_proc['ICD9_CODE'].str.startswith(diabetes_codes)

In [15]:
df_interf = df_diagnoses_proc.groupby(['SUBJECT_ID'])['code_interf'].any().rename('interf').reset_index()
df_interf

       SUBJECT_ID  interf
0               2   False
1               3    True
2               4   False
3               5   False
4               6    True
...           ...     ...
46512       99985    True
46513       99991    True
46514       99992    True
46515       99995    True
46516       99999    True

[46517 rows x 2 columns]

In [16]:
df_interf['interf'].value_counts(normalize=True)

interf
True     0.709354
False    0.290646
Name: proportion, dtype: float64

In [17]:
df_diab = df_diagnoses_proc.groupby(['SUBJECT_ID', 'HADM_ID'], sort=True)['code_diab'].any().rename('diab').reset_index()
df_diab

       SUBJECT_ID  HADM_ID   diab
0               2   163353  False
1               3   145834  False
2               4   185777  False
3               5   178980  False
4               6   107064  False
...           ...      ...    ...
58924       99985   176670  False
58925       99991   151118   True
58926       99992   197084  False
58927       99995   137810   True
58928       99999   113369   True

[58929 rows x 3 columns]

In [18]:
# tqdm.pandas()

In [19]:
def mark_uncertain(df: pd.DataFrame):
    df.loc[:, 'unk'] = False
    if df['diab'].any() and not df['diab'].iloc[0]:
        first_diag = df['diab'].idxmax()
        df.loc[:first_diag-1, 'unk'] = True
    return df


df_diab_unk = df_diab.groupby('SUBJECT_ID')[['HADM_ID', 'diab']].apply(mark_uncertain).reset_index(level=1, drop=True).reset_index()
df_diab_unk

       SUBJECT_ID  HADM_ID   diab    unk
0               2   163353  False  False
1               3   145834  False  False
2               4   185777  False  False
3               5   178980  False  False
4               6   107064  False  False
...           ...      ...    ...    ...
58924       99985   176670  False  False
58925       99991   151118   True  False
58926       99992   197084  False  False
58927       99995   137810   True  False
58928       99999   113369   True  False

[58929 rows x 4 columns]

In [20]:
df_flags = pd.merge(df_diab_unk, df_interf, how='left', left_on='SUBJECT_ID', right_on='SUBJECT_ID')
df_flags

       SUBJECT_ID  HADM_ID   diab    unk  interf
0               2   163353  False  False   False
1               3   145834  False  False    True
2               4   185777  False  False   False
3               5   178980  False  False   False
4               6   107064  False  False    True
...           ...      ...    ...    ...     ...
58924       99985   176670  False  False    True
58925       99991   151118   True  False    True
58926       99992   197084  False  False    True
58927       99995   137810   True  False    True
58928       99999   113369   True  False    True

[58929 rows x 5 columns]

In [21]:
df_flags['diab'].value_counts(normalize=True)

diab
False    0.758659
True     0.241341
Name: proportion, dtype: float64

In [22]:
discard = df_flags['interf'] | df_flags['unk']
control = ~discard & ~df_flags['diab']
diabetic = ~discard & df_flags['diab']

df_class = df_flags.copy()
df_class['class'] = pd.NA
df_class.loc[control, 'class'] = 'control'
df_class.loc[diabetic, 'class'] = 'diab'
df_class = df_class.drop(columns=['diab', 'unk', 'interf']).dropna().reset_index(drop=True)
df_class

       SUBJECT_ID  HADM_ID    class
0               2   163353  control
1               4   185777  control
2               5   178980  control
3               7   118037  control
4               8   159514  control
...           ...      ...      ...
14235       99836   101018  control
14236       99837   197195  control
14237       99928   104802     diab
14238       99934   176121  control
14239       99973   150202  control

[14240 rows x 3 columns]

In [23]:
(df_flags['interf'] & df_flags['diab']).sum() / df_flags['diab'].sum()

np.float64(0.953522711292364)

In [24]:
(df_flags['interf'] & ~df_flags['diab']).sum() / (~df_flags['diab']).sum()

np.float64(0.6959983895139463)

In [25]:
df_class['class'].value_counts(normalize=True)

class
control    0.953581
diab       0.046419
Name: proportion, dtype: float64

In [26]:
df_admissions_xyz = pd.merge(df_admissions, df_class, how='inner', on=['SUBJECT_ID', 'HADM_ID'])
df_admissions_xyz

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA,class
0,2,163353,2138-07-17 19:04:00,2138-07-21 15:48:00,NaT,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,NaN,NOT SPECIFIED,NaN,ASIAN,NaT,NaT,NEWBORN,0,1,control
1,4,185777,2191-03-16 00:28:00,2191-03-23 18:41:00,NaT,EMERGENCY,EMERGENCY ROOM ADMIT,HOME WITH HOME IV PROVIDR,Private,NaN,PROTESTANT QUAKER,SINGLE,WHITE,2191-03-15 13:10:00,2191-03-16 01:10:00,"FEVER,DEHYDRATION,FAILURE TO THRIVE",0,1,control
2,5,178980,2103-02-02 04:31:00,2103-02-04 12:15:00,NaT,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,NaN,BUDDHIST,NaN,ASIAN,NaT,NaT,NEWBORN,0,1,control
3,7,118037,2121-05-23 15:05:00,2121-05-27 11:57:00,NaT,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,NaN,CATHOLIC,NaN,WHITE,NaT,NaT,NEWBORN,0,1,control
4,8,159514,2117-11-20 10:22:00,2117-11-24 14:20:00,NaT,NEWBORN,PHYS REFERRAL/NORMAL DELI,HOME,Private,NaN,CATHOLIC,NaN,WHITE,NaT,NaT,NEWBORN,0,1,control
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14235,99836,101018,2116-05-21 19:23:00,2116-07-17 16:30:00,NaT,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOSPICE-MEDICAL FACILITY,Medicare,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
14236,99837,197195,2184-04-05 01:14:00,2184-04-09 12:58:00,NaT,EMERGENCY,CLINIC REFERRAL/PREMATURE,OTHER FACILITY,Medicaid,ENGL,UNOBTAINABLE,SINGLE,WHITE,2184-04-05 00:31:00,2184-04-05 02:45:00,ALTERED MENTAL STATUS,0,1,control
14237,99928,104802,2181-11-16 16:20:00,2181-11-18 14:13:00,NaT,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Medicaid,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2181-11-16 14:28:00,2181-11-16 17:20:00,DIABETIC KETOACIDOSIS,0,1,diab
14238,99934,176121,2110-02-28 03:47:00,2110-03-06 14:31:00,NaT,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Private,ENGL,NOT SPECIFIED,SINGLE,WHITE,NaT,NaT,PELVIC ABSCESS,0,1,control
14239,99973,150202,2180-11-27 02:30:00,2180-12-01 13:42:00,NaT,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Private,ENGL,CATHOLIC,MARRIED,WHITE,2180-11-26 21:22:00,2180-11-27 03:36:00,SEPSIS,0,1,control

In [27]:
df_waveforms_xyz = df_waveforms_filt[df_waveforms_filt['subject_id'].isin(df_class['SUBJECT_ID'])]
df_waveforms_xyz

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id
10158,1457,2194-10-15 19:02:00,3747397_0005,5226.0,"['II', 'ABP', 'PLETH']",p001457-2194-10-15-19-02
10162,1457,2194-10-15 19:02:00,3747397_0009,12715.0,"['II', 'ABP', 'PLETH']",p001457-2194-10-15-19-02
10164,1457,2194-10-15 19:02:00,3747397_0011,13721.0,"['II', 'PLETH', 'ABP']",p001457-2194-10-15-19-02
21158,2974,2171-03-27 02:26:00,3289928_0011,4474.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26
21160,2974,2171-03-27 02:26:00,3289928_0013,693.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26
...,...,...,...,...,...,...
846724,99836,2116-07-03 10:36:00,3585140_0017,25985.0,"['RESP', 'ABP', 'PLETH', 'CVP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36
846726,99836,2116-07-03 10:36:00,3585140_0019,19592.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36
846728,99836,2116-07-03 10:36:00,3585140_0021,94879.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36
846731,99836,2116-07-03 10:36:00,3585140_0024,19183.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36
846734,99836,2116-07-03 10:36:00,3585140_0027,3981.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36

In [28]:
def assign_admission(df: pd.DataFrame):
    df_xyz = df_admissions_xyz[df_admissions_xyz['SUBJECT_ID'] == df.name]
    matched_hadm_ids = []
    for record_start in df['record_start']:
        matched_hadm_id = pd.NA
        for admit, disch, hadm_id in df_xyz[['ADMITTIME', 'DISCHTIME', 'HADM_ID']].itertuples(index=False):
            if admit < record_start < disch:
                matched_hadm_id = hadm_id
                break
        matched_hadm_ids.append(matched_hadm_id)
    df['hadm_id'] = matched_hadm_ids
    return df


# df_waveforms_matched = df_waveforms_xyz.groupby('subject_id').progress_apply(assign_admission)
df_waveforms_matched = df_waveforms_xyz.groupby('subject_id').apply(assign_admission)
df_waveforms_matched = df_waveforms_matched.dropna().reset_index(drop=True)
df_waveforms_matched

/tmp/ipykernel_55809/1742793081.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_waveforms_matched = df_waveforms_xyz.groupby('subject_id').apply(assign_admission)

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id,hadm_id
0,2974,2171-03-27 02:26:00,3289928_0011,4474.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26,126804
1,2974,2171-03-27 02:26:00,3289928_0013,693.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26,126804
2,8061,2148-12-03 15:01:00,3145453_0019,1255.0,"['ABP', 'RESP', 'PLETH', 'I', 'V', 'II']",p008061-2148-12-03-15-01,133667
3,8061,2148-12-03 15:01:00,3145453_0020,12471.0,"['ABP', 'RESP', 'PLETH', 'I', 'V', 'II', 'CVP']",p008061-2148-12-03-15-01,133667
4,9124,2137-10-13 11:22:00,3576649_0004,13076.0,"['RESP', 'II', 'V', 'AVR', 'PLETH', 'ABP']",p009124-2137-10-13-11-22,142434
...,...,...,...,...,...,...,...
3972,99836,2116-07-03 10:36:00,3585140_0017,25985.0,"['RESP', 'ABP', 'PLETH', 'CVP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018
3973,99836,2116-07-03 10:36:00,3585140_0019,19592.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018
3974,99836,2116-07-03 10:36:00,3585140_0021,94879.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018
3975,99836,2116-07-03 10:36:00,3585140_0024,19183.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018
3976,99836,2116-07-03 10:36:00,3585140_0027,3981.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018

In [29]:
df_waveforms_class = pd.merge(df_waveforms_matched,
                              df_admissions_xyz,
                              how='inner',
                              left_on=['subject_id', 'hadm_id'],
                              right_on=['SUBJECT_ID', 'HADM_ID'])
df_waveforms_class

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id,hadm_id,SUBJECT_ID,HADM_ID,ADMITTIME,...,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA,class
0,2974,2171-03-27 02:26:00,3289928_0011,4474.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26,126804,2974,126804,2171-03-27 00:50:00,...,PORT,CATHOLIC,SINGLE,HISPANIC OR LATINO,2171-03-26 22:18:00,2171-03-27 02:01:00,PULSELESS ARREST,0,1,control
1,2974,2171-03-27 02:26:00,3289928_0013,693.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26,126804,2974,126804,2171-03-27 00:50:00,...,PORT,CATHOLIC,SINGLE,HISPANIC OR LATINO,2171-03-26 22:18:00,2171-03-27 02:01:00,PULSELESS ARREST,0,1,control
2,8061,2148-12-03 15:01:00,3145453_0019,1255.0,"['ABP', 'RESP', 'PLETH', 'I', 'V', 'II']",p008061-2148-12-03-15-01,133667,8061,133667,2148-12-03 00:49:00,...,NaN,NOT SPECIFIED,NaN,WHITE,2148-12-02 22:15:00,2148-12-03 02:10:00,"THROMBOCYTOPENIA,HYPOXIA",1,1,diab
3,8061,2148-12-03 15:01:00,3145453_0020,12471.0,"['ABP', 'RESP', 'PLETH', 'I', 'V', 'II', 'CVP']",p008061-2148-12-03-15-01,133667,8061,133667,2148-12-03 00:49:00,...,NaN,NOT SPECIFIED,NaN,WHITE,2148-12-02 22:15:00,2148-12-03 02:10:00,"THROMBOCYTOPENIA,HYPOXIA",1,1,diab
4,9124,2137-10-13 11:22:00,3576649_0004,13076.0,"['RESP', 'II', 'V', 'AVR', 'PLETH', 'ABP']",p009124-2137-10-13-11-22,142434,9124,142434,2137-10-13 10:17:00,...,NaN,CATHOLIC,SINGLE,WHITE,2137-10-13 09:19:00,2137-10-13 11:10:00,PNEUMONIA,0,1,diab
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3972,99836,2116-07-03 10:36:00,3585140_0017,25985.0,"['RESP', 'ABP', 'PLETH', 'CVP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3973,99836,2116-07-03 10:36:00,3585140_0019,19592.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3974,99836,2116-07-03 10:36:00,3585140_0021,94879.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3975,99836,2116-07-03 10:36:00,3585140_0024,19183.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3976,99836,2116-07-03 10:36:00,3585140_0027,3981.0,"['PLETH', 'RESP', 'CVP', 'ABP', 'II', 'V', 'AVR']",p099836-2116-07-03-10-36,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control

In [30]:
# elective = df_waveforms_class['ADMISSION_TYPE'] == 'ELECTIVE' # and not NEWBORN
# df_final = df_waveforms_class[elective]
df_final = df_waveforms_class.copy()
df_final = df_final.sort_values(['subject_id', 'segment_time'], ascending=[True, False])
df_final

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id,hadm_id,SUBJECT_ID,HADM_ID,ADMITTIME,...,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA,class
0,2974,2171-03-27 02:26:00,3289928_0011,4474.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26,126804,2974,126804,2171-03-27 00:50:00,...,PORT,CATHOLIC,SINGLE,HISPANIC OR LATINO,2171-03-26 22:18:00,2171-03-27 02:01:00,PULSELESS ARREST,0,1,control
1,2974,2171-03-27 02:26:00,3289928_0013,693.0,"['II', 'V', 'ABP', 'PLETH']",p002974-2171-03-27-02-26,126804,2974,126804,2171-03-27 00:50:00,...,PORT,CATHOLIC,SINGLE,HISPANIC OR LATINO,2171-03-26 22:18:00,2171-03-27 02:01:00,PULSELESS ARREST,0,1,control
3,8061,2148-12-03 15:01:00,3145453_0020,12471.0,"['ABP', 'RESP', 'PLETH', 'I', 'V', 'II', 'CVP']",p008061-2148-12-03-15-01,133667,8061,133667,2148-12-03 00:49:00,...,NaN,NOT SPECIFIED,NaN,WHITE,2148-12-02 22:15:00,2148-12-03 02:10:00,"THROMBOCYTOPENIA,HYPOXIA",1,1,diab
2,8061,2148-12-03 15:01:00,3145453_0019,1255.0,"['ABP', 'RESP', 'PLETH', 'I', 'V', 'II']",p008061-2148-12-03-15-01,133667,8061,133667,2148-12-03 00:49:00,...,NaN,NOT SPECIFIED,NaN,WHITE,2148-12-02 22:15:00,2148-12-03 02:10:00,"THROMBOCYTOPENIA,HYPOXIA",1,1,diab
9,9124,2137-10-13 11:22:00,3576649_0016,51867.0,"['ABP', 'RESP', 'PLETH', 'II', 'V', 'AVR']",p009124-2137-10-13-11-22,142434,9124,142434,2137-10-13 10:17:00,...,NaN,CATHOLIC,SINGLE,WHITE,2137-10-13 09:19:00,2137-10-13 11:10:00,PNEUMONIA,0,1,diab
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3941,99836,2116-06-28 21:17:00,3477769_0208,590.0,"['PLETH', 'RESP', 'ABP', 'II', 'V', 'AVR', 'CVP']",p099836-2116-06-28-21-17,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3877,99836,2116-06-28 21:17:00,3477769_0011,414.0,"['RESP', 'ABP', 'PLETH', 'II', 'V', 'AVR']",p099836-2116-06-28-21-17,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3933,99836,2116-06-28 21:17:00,3477769_0174,411.0,"['RESP', 'ABP', 'PLETH', 'CVP', 'II', 'V', 'AVR']",p099836-2116-06-28-21-17,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3919,99836,2116-06-28 21:17:00,3477769_0124,358.0,"['RESP', 'ABP', 'CVP', 'II', 'V', 'AVR', 'PLETH']",p099836-2116-06-28-21-17,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control
3887,99836,2116-06-28 21:17:00,3477769_0031,322.0,"['RESP', 'ABP', 'PLETH', 'II', 'V', 'AVR']",p099836-2116-06-28-21-17,101018,99836,101018,2116-05-21 19:23:00,...,ENGL,CATHOLIC,NaN,UNABLE TO OBTAIN,NaT,NaT,HEPATITIS,0,1,control

In [31]:
df_final['subject_id'].nunique()

256

In [32]:
df_final['class'].value_counts()

class
control    3477
diab        500
Name: count, dtype: int64

In [33]:
df_final[df_final['class'] == 'diab']['subject_id'].nunique()

17

In [34]:
samples_per_class = 17

In [82]:
df_final[df_final['subject_id'] == 90902]

,subject_id,record_start,segment_id,segment_time,segment_signals,master_id,hadm_id,SUBJECT_ID,HADM_ID,ADMITTIME,...,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA,class
3397,90902,2142-09-24 17:16:00,3545763_0023,56296.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3392,90902,2142-09-24 17:16:00,3545763_0010,29363.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3393,90902,2142-09-24 17:16:00,3545763_0013,21221.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3395,90902,2142-09-24 17:16:00,3545763_0018,14652.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3394,90902,2142-09-24 17:16:00,3545763_0016,13395.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3398,90902,2142-09-24 17:16:00,3545763_0026,6460.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3391,90902,2142-09-24 17:16:00,3545763_0007,2775.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3396,90902,2142-09-24 17:16:00,3545763_0021,2343.0,"['RESP', 'ABP', 'PLETH', 'II', 'III', 'V']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab
3390,90902,2142-09-24 17:16:00,3545763_0005,1961.0,"['PLETH', 'RESP', 'II', 'III', 'V', 'ABP']",p090902-2142-09-24-17-16,155876,90902,155876,2142-09-23 21:02:00,...,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2142-09-23 16:33:00,2142-09-23 21:56:00,SUBDURAL HEMATOMA,0,1,diab

In [36]:
skip_subjects = [94484]
skip_segments = [
    '3771199_0011', '3771199_0013', # 83817
    '3178762_0005', # 54132
    '3260530_0008', # 60747
    '3602666_0129', # 47874
    # '3545763_0023', '3545763_0010', '3545763_0013', '3545763_0018', '3545763_0016', '3545763_0026', '3545763_0007', '3545763_0021' # 90902
]

df_filt = df_final[(~df_final['subject_id'].isin(skip_subjects)) & (~df_final['segment_id'].isin(skip_segments))]

df_control = df_filt[df_filt['class'] == 'control'].groupby('subject_id').head(n=1).sample(n=samples_per_class, random_state=0)
df_diab = df_filt[df_filt['class'] == 'diab'].groupby('subject_id').head(n=1).sample(n=samples_per_class, random_state=0)
df_subjects = pd.concat((df_control, df_diab), axis=0)[['subject_id', 'record_start', 'segment_id', 'segment_time', 'master_id', 'class']]
df_subjects = df_subjects.reset_index(drop=True).sort_values(['class', 'subject_id'])
df_subjects

,subject_id,record_start,segment_id,segment_time,master_id,class
8,48480,2116-05-04 17:50:00,3876369_0016,49774.000,p048480-2116-05-04-17-50,control
13,63646,2177-05-29 11:39:00,3089087_0007,42791.000,p063646-2177-05-29-11-39,control
2,64485,2168-10-15 13:24:00,3625999_0008,65231.000,p064485-2168-10-15-13-24,control
3,64916,2102-02-22 16:40:00,3181603_0003,39206.000,p064916-2102-02-22-16-40,control
10,66682,2130-05-10 12:40:00,3549618_0015,39738.000,p066682-2130-05-10-12-40,control
6,67763,2163-09-18 02:36:00,3295996_0009,36611.000,p067763-2163-09-18-02-36,control
4,69006,2174-02-05 18:35:00,3098482_0012,55723.000,p069006-2174-02-05-18-35,control
1,76178,2109-12-20 20:52:00,3045819_0010,42634.000,p076178-2109-12-20-20-52,control
15,76237,2128-09-16 10:40:00,3670140_0003,128277.000,p076237-2128-09-16-10-40,control
14,81633,2118-12-25 07:43:00,3588494_0011,61101.000,p081633-2118-12-25-07-43,control
11,82245,2151-04-18 14:32:00,3407528_0005,72965.000,p082245-2151-04-18-14-32,control
0,83263,2145-12-08 23:07:00,3461856_0017,57166.000,p083263-2145-12-08-23-07,control
16,83817,2179-07-26 12:44:00,3771199_0015,14037.000,p083817-2179-07-26-12-44,control
9,87470,2161-02-22 16:12:00,3376165_0378,6417.000,p087470-2161-02-22-16-12,control
7,93566,2128-12-24 10:43:00,3385437_0039,31700.000,p093566-2128-12-24-10-43,control
12,94147,2192-02-25 08:47:00,3954762_0029,32679.000,p094147-2192-02-25-08-47,control
5,96350,2166-06-27 11:22:00,3865027_0027,43989.000,p096350-2166-06-27-11-22,control
30,8061,2148-12-03 15:01:00,3145453_0020,12471.000,p008061-2148-12-03-15-01,diab
17,9124,2137-10-13 11:22:00,3576649_0016,51867.000,p009124-2137-10-13-11-22,diab
23,10842,2155-03-13 18:08:00,3523295_0005,49030.000,p010842-2155-03-13-18-08,diab
29,40435,2167-11-09 20:05:00,3075521_0044,41442.000,p040435-2167-11-09-20-05,diab
22,40724,2194-12-26 19:06:00,3023009_0005,57086.000,p040724-2194-12-26-19-06,diab
31,47874,2177-08-06 17:46:00,3602666_0050,33867.000,p047874-2177-08-06-17-46,diab
18,54132,2114-07-24 03:07:00,3178762_0004,27961.344,p054132-2114-07-24-03-07,diab
26,54586,2168-03-09 10:43:00,3860079_0019,44011.000,p054586-2168-03-09-10-43,diab
19,60747,2188-08-29 15:31:00,3260530_0003,27109.000,p060747-2188-08-29-15-31,diab
20,61642,2165-04-22 15:43:00,3102184_0065,9700.000,p061642-2165-04-22-15-43,diab
25,63402,2115-10-17 13:11:00,3496554_0025,7122.000,p063402-2115-10-17-13-11,diab
28,65728,2120-02-15 14:23:00,3034248_0015,16262.000,p065728-2120-02-15-14-23,diab
33,81037,2172-05-16 02:08:00,3281981_0011,32731.000,p081037-2172-05-16-02-08,diab
21,82187,2148-09-24 00:52:00,3527335_0007,36241.000,p082187-2148-09-24-00-52,diab
24,89782,2110-08-27 18:51:00,3535449_0001,48938.000,p089782-2110-08-27-18-51,diab
32,90902,2142-09-24 17:16:00,3545763_0023,56296.000,p090902-2142-09-24-17-16,diab
27,98484,2131-11-20 09:44:00,3465056_0001,37613.000,p098484-2131-11-20-09-44,diab

In [54]:
for sid in df_subjects['subject_id']:
    # display(df_final[df_final['subject_id'] == sid])
    print(sid, df_final.loc[df_final['subject_id'] == sid]['segment_signals'].str.contains('RESP').any())

48480 False
63646 True
64485 False
64916 True
66682 True
67763 True
69006 True
76178 False
76237 True
81633 True
82245 False
83263 True
83817 False
87470 True
93566 True
94147 True
96350 True
8061 True
9124 True
10842 True
40435 True
40724 True
47874 True
54132 False
54586 True
60747 True
61642 True
63402 True
65728 True
81037 False
82187 True
89782 False
90902 True
98484 True

In [116]:
df_subjects.to_csv('csvs/subjects.csv', index=False)

----
fetching subjects data

In [114]:
for subject_id, record_start, segment_id, _, master_id, label in df_subjects.itertuples(index=False):
    pid = f'p{subject_id:06d}'
    original_folder: Path = mimic_root / pid[:3] / pid
    new_folder: Path = dataset_root / label / pid
    # shutil.copytree(original_folder, new_folder, dirs_exist_ok=True)
    try:
        shutil.copytree(original_folder, new_folder)
    except FileExistsError as e:
        print(e)
    subprocess.run(['wget', '-N', '-c', '-np', '--show-progress', '-P', new_folder.as_posix(), '-nd', f'https://physionet.org/files/mimic3wdb-matched/1.0/{pid[:3]}/{pid}/{master_id}.hea'])
    subprocess.run(['wget', '-N', '-c', '-np', '--show-progress', '-P', new_folder.as_posix(), '-nd', f'https://physionet.org/files/mimic3wdb-matched/1.0/{pid[:3]}/{pid}/{segment_id}.hea'])
    subprocess.run(['wget', '-N', '-c', '-np', '--show-progress', '-P', new_folder.as_posix(), '-nd', f'https://physionet.org/files/mimic3wdb-matched/1.0/{pid[:3]}/{pid}/{segment_id}.dat'])

--2026-01-16 16:26:23--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/p048480-2116-05-04-17-50.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/p048480-2116-05-04-17-50.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:24--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3876369_0016.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/3876369_0016.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:25--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3876369_0016.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/3876369_0016.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:26--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p063646/p063646-2177-05-29-11-39.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p063646/p063646-2177-05-29-11-39.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:26--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p063646/3089087_0007.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p063646/3089087_0007.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:27--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p063646/3089087_0007.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p063646/3089087_0007.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:28--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p064485/p064485-2168-10-15-13-24.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p064485/p064485-2168-10-15-13-24.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:28--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p064485/3625999_0008.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p064485/3625999_0008.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:29--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p064485/3625999_0008.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p064485/3625999_0008.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:30--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p064916/p064916-2102-02-22-16-40.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p064916/p064916-2102-02-22-16-40.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:31--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p064916/3181603_0003.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p064916/3181603_0003.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:31--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p064916/3181603_0003.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p064916/3181603_0003.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:32--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p066682/p066682-2130-05-10-12-40.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p066682/p066682-2130-05-10-12-40.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:33--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p066682/3549618_0015.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p066682/3549618_0015.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:33--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p066682/3549618_0015.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p066682/3549618_0015.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:34--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p067763/p067763-2163-09-18-02-36.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p067763/p067763-2163-09-18-02-36.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:35--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p067763/3295996_0009.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p067763/3295996_0009.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:36--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p067763/3295996_0009.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p067763/3295996_0009.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:36--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p069006/p069006-2174-02-05-18-35.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p069006/p069006-2174-02-05-18-35.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:37--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p069006/3098482_0012.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p069006/3098482_0012.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:38--  https://physionet.org/files/mimic3wdb-matched/1.0/p06/p069006/3098482_0012.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p069006/3098482_0012.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:38--  https://physionet.org/files/mimic3wdb-matched/1.0/p07/p076178/p076178-2109-12-20-20-52.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p076178/p076178-2109-12-20-20-52.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:39--  https://physionet.org/files/mimic3wdb-matched/1.0/p07/p076178/3045819_0010.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p076178/3045819_0010.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:40--  https://physionet.org/files/mimic3wdb-matched/1.0/p07/p076178/3045819_0010.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p076178/3045819_0010.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:40--  https://physionet.org/files/mimic3wdb-matched/1.0/p07/p076237/p076237-2128-09-16-10-40.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p076237/p076237-2128-09-16-10-40.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:41--  https://physionet.org/files/mimic3wdb-matched/1.0/p07/p076237/3670140_0003.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p076237/3670140_0003.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:42--  https://physionet.org/files/mimic3wdb-matched/1.0/p07/p076237/3670140_0003.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p076237/3670140_0003.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:43--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p081633/p081633-2118-12-25-07-43.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p081633/p081633-2118-12-25-07-43.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:43--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p081633/3588494_0011.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p081633/3588494_0011.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:44--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p081633/3588494_0011.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p081633/3588494_0011.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:45--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p082245/p082245-2151-04-18-14-32.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p082245/p082245-2151-04-18-14-32.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:45--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p082245/3407528_0005.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p082245/3407528_0005.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:46--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p082245/3407528_0005.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p082245/3407528_0005.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:47--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p083263/p083263-2145-12-08-23-07.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p083263/p083263-2145-12-08-23-07.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:48--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p083263/3461856_0017.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p083263/3461856_0017.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:48--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p083263/3461856_0017.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p083263/3461856_0017.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:49--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p083817/p083817-2179-07-26-12-44.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p083817/p083817-2179-07-26-12-44.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:50--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p083817/3771199_0015.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p083817/3771199_0015.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:50--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p083817/3771199_0015.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p083817/3771199_0015.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:51--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p087470/p087470-2161-02-22-16-12.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p087470/p087470-2161-02-22-16-12.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:52--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p087470/3376165_0378.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p087470/3376165_0378.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:52--  https://physionet.org/files/mimic3wdb-matched/1.0/p08/p087470/3376165_0378.dat
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p087470/3376165_0378.dat’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:53--  https://physionet.org/files/mimic3wdb-matched/1.0/p09/p093566/p093566-2128-12-24-10-43.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p093566/p093566-2128-12-24-10-43.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:26:54--  https://physionet.org/files/mimic3wdb-matched/1.0/p09/p093566/3385437_0039.hea
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p093566/3385437_0039.hea’ não foi modificado no servidor. Não será baixado.


In [117]:
for subject_id, record_start, segment_id, _, master_id, label in df_subjects.itertuples(index=False):
    pid = f'p{subject_id:06d}'
    original_folder: Path = mimic_root / pid[:3] / pid
    new_folder: Path = dataset_root / label / pid
    # shutil.copytree(original_folder, new_folder, dirs_exist_ok=True)
    try:
        shutil.copytree(original_folder, new_folder)
    except FileExistsError as e:
        print(e)
    subprocess.run(['wget', '-r', '-N', '-c', '-np', '--show-progress', '-P', new_folder.as_posix(), '-nd', f'https://physionet.org/files/mimic3wdb-matched/1.0/{pid[:3]}/{pid}/'])

[Errno 17] File exists: '/home/thulio/projects/masters-research/data/control/p048480'

--2026-01-16 16:30:06--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/
Resolvendo physionet.org (physionet.org)... 18.18.42.54
Conectando-se a physionet.org (physionet.org)|18.18.42.54|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: não especificada [text/html]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/index.html’

     0K .......... .......... .....                            1023K=0,03s

Está faltando o cabeçalho Last-modified -- horários desligados.
2026-01-16 16:30:06 (1023 KB/s) - ‘/home/thulio/projects/masters-research/data/control/p048480/index.html’ salvo [26555]

Carregando robots.txt; por favor ignore qualquer erro.
--2026-01-16 16:30:06--  https://physionet.org/robots.txt
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 22 [text/plain]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/robots.txt’

     0K                                                       100% 22,8M=0s

2026-01-16 16:30:07 (22,8 MB/s) - ‘/home/thulio/projects/masters-research/data/control/p048480/robots.txt’ salvo [22/22]

--2026-01-16 16:30:07--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0001.dat
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 6095 (6,0K) [application/octet-stream]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0001.dat’

     0K .....                                                 100% 1,19G=0s

2026-01-16 16:30:07 (1,19 GB/s) - ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0001.dat’ salvo [6095/6095]

--2026-01-16 16:30:07--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0001.hea
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0001.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:30:07--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0002.dat
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 2250 (2,2K) [application/octet-stream]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0002.dat’

     0K ..                                                    100% 2,61G=0s

2026-01-16 16:30:07 (2,61 GB/s) - ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0002.dat’ salvo [2250/2250]

--2026-01-16 16:30:07--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0002.hea
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0002.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:30:07--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0003.dat
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 13000 (13K) [application/octet-stream]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0003.dat’

     0K .......... ..                                         100% 1,67G=0s

2026-01-16 16:30:08 (1,67 GB/s) - ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0003.dat’ salvo [13000/13000]

--2026-01-16 16:30:08--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0003.hea
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0003.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:30:08--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0004.dat
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 359250 (351K) [application/octet-stream]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0004.dat’

     0K .......... .......... .......... .......... .......... 14%  286K 1s
    50K .......... .......... .......... .......... .......... 28%  128K 1s
   100K .......... .......... .......... .......... .......... 42%  441M 1s
   150K .......... .......... .......... .......... .......... 57%  480K 1s
   200K .......... .......... .......... .......... .......... 71% 13,8M 0s
   250K .......... .......... .......... .......... .......... 85%  392K 0s
   300K .......... .......... .......... .......... .......... 99%  404K 0s
   350K                                                       100% 1,55T=0,9s

2026-01-16 16:30:09 (379 KB/s) - ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0004.dat’ salvo [359250/359250]

--2026-01-16 16:30:09--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0004.hea
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0004.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:30:09--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0005.dat
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 2000 (2,0K) [application/octet-stream]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0005.dat’

     0K .                                                     100% 2,82G=0s

2026-01-16 16:30:09 (2,82 GB/s) - ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0005.dat’ salvo [2000/2000]

--2026-01-16 16:30:09--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0005.hea
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 304 Not Modified
Arquivo ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0005.hea’ não foi modificado no servidor. Não será baixado.

--2026-01-16 16:30:09--  https://physionet.org/files/mimic3wdb-matched/1.0/p04/p048480/3555979_0006.dat
Reaproveitando a conexão existente para physionet.org:443.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 3516500 (3,4M) [application/octet-stream]
Salvando em: ‘/home/thulio/projects/masters-research/data/control/p048480/3555979_0006.dat’

     0K .......... .......... .......... .......... ..........  1%  213K 16s
    50K .......... .......... .......... .......... ..........  2% 3,43M 8s
   100K .......... .......... .......... .......... ..........  4%  279K 9s
   150K .......... .......... .......... .......... ..........  5%  306K 10s
   200K .......... .......... .......... .......... ..........  7%  320K 10s
   250K .......... .......... .......... .......... ..........  8%  332K 9s
   300K .......... .......... .......... .......... .......... 10%  317K 9s
   350K .......... .......... .......... .......... .......... 11%  265K 9s
   400K .......... .......... .......... .......... .......... 13%  338K 9s
   450K .......... .......... .......... .......... .......... 14%  341K 9s
   500K .......... .......... .......... .......... .......... 16%  339K 9s
   550K .......... .......... .......... .......... .......... 17%  351K 9s
   600K .......... .......... .......... .......... .......... 18%  347K 8s
   650K .......... .......... .......... .......... .......... 20%  346K 8s
   700K .......... .......... .......... .......... .......... 21%  358K 8s
   750K .......... .......... .......... .......... .......... 23%  264K 8s
   800K .......... .......... .......... .......... .......

KeyboardInterrupt: